//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Route53Updater.Tests {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleEvents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleEvents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Route53Updater.Tests.SampleEvents", typeof(SampleEvents).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Version&quot;: &quot;0&quot;,
        ///    &quot;Id&quot;: &quot;8711b63b-88ab-98bf-9ea6-cfbf9c6dc425&quot;,
        ///    &quot;DetailType&quot;: null,
        ///    &quot;Source&quot;: &quot;aws.ec2&quot;,
        ///    &quot;Account&quot;: &quot;123456789012&quot;,
        ///    &quot;Time&quot;: &quot;2017-10-06T12:51:07Z&quot;,
        ///    &quot;Region&quot;: &quot;eu-west-1&quot;,
        ///    &quot;Resources&quot;: [
        ///        &quot;arn:aws:ec2:us-east-1:123456789012:instance/i-abcd1111&quot;
        ///    ],
        ///    &quot;Detail&quot;: {
        ///        &quot;instance-id&quot;: &quot;i-abcd1111&quot;,
        ///        &quot;State&quot;: &quot;running&quot;
        ///    }
        ///}.
        /// </summary>
        internal static string RunningEvent {
            get {
                return ResourceManager.GetString("RunningEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;0&quot;,
        ///  &quot;id&quot;: &quot;7bf73129-1428-4cd3-a780-95db273d1602&quot;,
        ///  &quot;detail-type&quot;: &quot;EC2 Instance State-change Notification&quot;,
        ///  &quot;source&quot;: &quot;aws.ec2&quot;,
        ///  &quot;account&quot;: &quot;123456789012&quot;,
        ///  &quot;time&quot;: &quot;2015-11-11T21:29:54Z&quot;,
        ///  &quot;region&quot;: &quot;us-east-1&quot;,
        ///  &quot;resources&quot;: [
        ///    &quot;arn:aws:ec2:us-east-1:123456789012:instance/i-abcd1111&quot;
        ///  ],
        ///  &quot;detail&quot;: {
        ///    &quot;instance-id&quot;: &quot;i-abcd1111&quot;,
        ///    &quot;state&quot;: &quot;stopping&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string StoppingEvent {
            get {
                return ResourceManager.GetString("StoppingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;0&quot;,
        ///  &quot;id&quot;: &quot;f74e985d-c3ff-415d-b5fa-d3614c5e3434&quot;,
        ///  &quot;detail-type&quot;: &quot;EC2 Instance State-change Notification&quot;,
        ///  &quot;source&quot;: &quot;aws.ec2&quot;,
        ///  &quot;account&quot;: &quot;123456789012&quot;,
        ///  &quot;time&quot;: &quot;2015-11-11T21:36:48Z&quot;,
        ///  &quot;region&quot;: &quot;us-east-1&quot;,
        ///  &quot;resources&quot;: [
        ///    &quot;arn:aws:ec2:us-east-1:123456789012:instance/i-abcd5555&quot;
        ///  ],
        ///  &quot;detail&quot;: {
        ///    &quot;instance-id&quot;: &quot;i-abcd5555&quot;,
        ///    &quot;state&quot;: &quot;terminated&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string TerminatedEvent {
            get {
                return ResourceManager.GetString("TerminatedEvent", resourceCulture);
            }
        }
    }
}
